Bump minimum supported Rust version to 1.63.0
Trying to compile on v1.48.0 now fails with:

```
Error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.6.4/Cargo.toml`
Caused by:
  failed to parse the `edition` key
```